### ISSUE TITLE
종목 필터링 제안

### ISSUE THREAD

**Issue by sjookwag** [taehyunjo90/gatherer#2]
안녕하세요,  ReadMe에 다음과 같은 말이 있어서 , 

" 예를들어, 현재는 코스피 전종목 호가,체결 틱 데이터는 수집 가능하지만 
내가 원하는 종목들을 선택해서 수집하는 기능은 구현되어 있지 않습니다. "

저는 종목코드 리스트를 startswith함수로 필터링하는 식으로 코드를 수정하는 게 어떨까 싶어요
(더 좋은 방법은 정규표현식이지만 )

```
def getGatheringInstance(codes):
    """
    나중에 옵션을 주어서 원하는 종목들만 받아올 수 있게 개선
    :return:
    """
    df_info = getWholeKoreanFuturesInfo()

    list_futcode = df_info.loc[:, '단축코드'] # 전 종목 가져오기
    # list_futcode = list(list_futcode)
    futcode = [ code for code in list_futcode if code.startswith( codes ) ]
....
```
이때 codes는 튜플(tuple)로 해야 합니다.  가령 **('101R9','104')** . startswith()가 리스트를 받지 않아서...

**Comment by taehyunjo90** [comment]
정말 늦게 확인했네요.
최근에 코드를 다시 한번 확인할 일이 생길 것 같은데, 그 때 반영해보도록 하겠습니다.
감사합니다.
